import { z } from "zod";

/**
 * Strict JSON schema for L2 model output.
 *
 * Phase 3: every field the model is allowed to return is validated with zod.
 * On parse failure runL2 retries once with a stricter system reminder, then
 * falls back to runL2Fallback. This catches: missing fields, wrong types,
 * out-of-range scores, and free-text where structured data is expected.
 */

export const CriterionScoreInputSchema = z.object({
  id: z.string().min(1),
  score: z.number().min(1).max(10),
  rationale: z.string().min(1),
  evidence_ids: z.array(z.string()).default([]),
  /** Mandatory anti-sycophancy field: at least one concrete reason this is not a band higher.
   *  Length reduced (10 → 5) to match real top-jury terseness ("Нет KPI", "Слабо"). */
  why_not_higher_band: z.string().min(5),
  /** Real top-jury comments don't always include a per-criterion fatal flaw
   *  (e.g. gold rationales like "Шикарный кейс" carry no weakness). Relaxed
   *  from min(1) → default empty so the model isn't forced to hallucinate
   *  flaws on legitimately strong criteria. */
  fatal_flaws: z.array(z.string().min(1)).default([]),
});

export const EvidenceGradeSchema = z
  .object({
    no_baseline: z.boolean().default(false),
    no_causality: z.boolean().default(false),
    no_attribution: z.boolean().default(false),
    /**
     * Model flags that a YoY / prior-period baseline is genuinely *not applicable*
     * to this case — brand-new product, first-of-kind instrument, one-off launch,
     * category that didn't exist before. When TRUE, the no_baseline cap is BYPASSED.
     * Must be paired with `baseline_not_applicable_reason` so the override is auditable.
     */
    baseline_not_applicable: z.boolean().default(false),
    baseline_not_applicable_reason: z.string().optional(),
    rationale: z.string().optional(),
  })
  .default({
    no_baseline: false,
    no_causality: false,
    no_attribution: false,
    baseline_not_applicable: false,
  });

/** Phase 5: structured avatar script. Enforces a 60–90s short version with
 *  explicit sections (hook → verdict → steelman → fatal flaw → close) plus a
 *  3-minute long version for full presentations. */
export const AvatarScriptSchema = z.object({
  short: z.string().min(80), // target 60–90s, tolerate compressed Russian down to ~25s
  long: z.string().min(250), // target 3 min, tolerate down to ~60s of dense speech
  sections: z.object({
    hook: z.string().min(5),
    verdict: z.string().min(5),
    steelman: z.string().min(5),
    fatal_flaw: z.string().min(5),
    close: z.string().min(5),
  }),
});

/** L2 scoring response. NOTE: avatar_script is intentionally NOT here.
 *  The speech is generated by a separate call (generateAvatarSpeech) AFTER
 *  caps fire and the final award level is known. This guarantees the speech
 *  always references the post-cap final score, not the model's preliminary
 *  pre-cap estimate. */
export const L2ResponseSchema = z.object({
  criteria: z.array(CriterionScoreInputSchema).min(1),
  social_outcomes_score: z.number().min(1).max(10).optional(),
  social_outcomes_rationale: z.string().optional(),
  evidence_grade: EvidenceGradeSchema.optional(),
  one_paragraph_verdict: z.string().min(1),
  /** Required: top fatal flaw across the whole case (single sentence). */
  case_fatal_flaw: z.string().min(5),
  /** Required: explicit reason this case does not deserve a band higher overall. */
  why_not_higher_band_overall: z.string().min(5),
});

export type L2Response = z.infer<typeof L2ResponseSchema>;
export type EvidenceGrade = z.infer<typeof EvidenceGradeSchema>;
export type CriterionScoreInput = z.infer<typeof CriterionScoreInputSchema>;
