import { getSupabase } from "./supabase.js";
import type { CoreOutput, CriterionScore } from "./types/evaluation.js";
import type { StoredFileRef } from "./storage.js";

/**
 * Typed DB layer over public.cases / public.verdicts. The rest of the app
 * speaks in StoredCase / StoredEvaluation; this module is the only place that
 * knows about Supabase row shapes and column names.
 *
 * Auth: service-role bypasses RLS. The API layer is responsible for filtering
 * by uploaded_by / role before calling these helpers.
 */

export interface StoredCase {
  case_id: string;
  created_at: string;
  external_case_id?: string;
  project_name?: string;
  brand?: string;
  agency?: string;
  block_id: string;
  nomination_id: string;
  year: number;
  text_fields: Record<string, string>;
  storage_paths: StoredFileRef[];
  status: CaseStatus;
}

export type CaseStatus = "uploaded" | "processing" | "scored" | "approved" | "rendered" | "failed";

export interface StoredEvaluation {
  evaluation_id: string;
  case_id: string;
  created_at: string;
  output: CoreOutput;
}

export interface NewCaseInput {
  external_case_id?: string;
  project_name?: string;
  nomination_id: string;
  block_id: string;
  year: number | string;
  text_fields: Record<string, string>;
  storage_paths: StoredFileRef[];
  uploaded_by?: string;
  /** Provenance tag — e.g. 'sm2025_import' for backtest cases. NULL for live uploads. */
  source?: string;
  /** Ground-truth jury award for backtest cases: gold|silver|bronze|shortlist|longlist|none. */
  historical_award?: string;
  /** Raw level2 jury scoring snapshot (criteries with weights/scores) for diff against our verdict. */
  historical_scores?: Record<string, unknown>;
}

interface CaseRow {
  id: string;
  external_case_id: string | null;
  project_name: string | null;
  brand: string | null;
  agency: string | null;
  block_id: string;
  nomination_id: string;
  year: number;
  text_fields: Record<string, string>;
  storage_paths: StoredFileRef[];
  status: CaseStatus;
  uploaded_by: string | null;
  uploaded_at: string;
  updated_at: string;
}

interface VerdictRow {
  id: string;
  case_id: string;
  block_id: string;
  total_score: number;
  award_level: "gold" | "silver" | "bronze" | "shortlist" | "longlist";
  one_paragraph_verdict: string;
  criteria_scores: Array<{ criterion_id: string; score: number; rationale: string; evidence_ids: string[] }>;
  missing_evidence: string[];
  consistency_check_passed: boolean;
  methodology_hash: string;
  anchors_hash: string;
  prompt_hash: string;
  input_hash: string;
  model_id: string;
  approval_state: "pending" | "approved" | "rejected";
  created_at: string;
}

function rowToStoredCase(row: CaseRow): StoredCase {
  return {
    case_id: row.id,
    created_at: row.uploaded_at,
    external_case_id: row.external_case_id ?? undefined,
    project_name: row.project_name ?? undefined,
    brand: row.brand ?? undefined,
    agency: row.agency ?? undefined,
    block_id: row.block_id,
    nomination_id: row.nomination_id,
    year: row.year,
    text_fields: row.text_fields ?? {},
    storage_paths: row.storage_paths ?? [],
    status: row.status,
  };
}

/** Insert a new case row (id auto-generated by DB). Returns the new case_id. */
export async function insertCase(input: NewCaseInput): Promise<string> {
  const sb = getSupabase();
  const yearNum = typeof input.year === "string" ? parseInt(input.year, 10) || new Date().getFullYear() : input.year;
  const { data, error } = await sb
    .from("cases")
    .insert({
      external_case_id: input.external_case_id ?? null,
      project_name: input.project_name ?? null,
      block_id: input.block_id,
      nomination_id: input.nomination_id,
      year: yearNum,
      text_fields: input.text_fields,
      storage_paths: input.storage_paths,
      status: "uploaded",
      uploaded_by: input.uploaded_by ?? null,
      source: input.source ?? null,
      historical_award: input.historical_award ?? null,
      historical_scores: input.historical_scores ?? null,
    })
    .select("id")
    .single();
  if (error || !data) throw new Error(`insertCase failed: ${error?.message ?? "no row"}`);
  return data.id as string;
}

export async function getCase(caseId: string): Promise<StoredCase | null> {
  const sb = getSupabase();
  const { data, error } = await sb.from("cases").select("*").eq("id", caseId).maybeSingle();
  if (error) throw new Error(`getCase failed: ${error.message}`);
  if (!data) return null;
  return rowToStoredCase(data as CaseRow);
}

export async function listCases(limit = 200): Promise<
  Array<{ case_id: string; project_name?: string; created_at: string; status: CaseStatus }>
> {
  const sb = getSupabase();
  const { data, error } = await sb
    .from("cases")
    .select("id, project_name, uploaded_at, status")
    .order("uploaded_at", { ascending: false })
    .limit(limit);
  if (error) throw new Error(`listCases failed: ${error.message}`);
  return (data ?? []).map((r: any) => ({
    case_id: r.id,
    project_name: r.project_name ?? undefined,
    created_at: r.uploaded_at,
    status: r.status,
  }));
}

export async function updateCaseStatus(caseId: string, status: CaseStatus): Promise<void> {
  const sb = getSupabase();
  const { error } = await sb.from("cases").update({ status, updated_at: new Date().toISOString() }).eq("id", caseId);
  if (error) throw new Error(`updateCaseStatus failed: ${error.message}`);
}

function criteriaScoresToRow(scores: CriterionScore[]): VerdictRow["criteria_scores"] {
  return scores.map((s) => ({
    criterion_id: s.criterion,
    score: s.score,
    rationale: s.rationale,
    evidence_ids: s.evidence_ids ?? [],
  }));
}

export interface NewEvidenceInput {
  case_id: string;
  kind: "pdf_page" | "video_frame" | "video_clip" | "audio_quote" | "text_field" | "extracted_text";
  source: string;
  snippet?: string;
  page_or_slide?: number;
  timestamp_ms?: number;
  storage_path?: string;
  metadata?: Record<string, unknown>;
}

/** Bulk-insert evidence rows for a case. Returns DB ids in input order. */
export async function insertEvidenceBatch(rows: NewEvidenceInput[]): Promise<string[]> {
  if (rows.length === 0) return [];
  const sb = getSupabase();
  const payload = rows.map((r) => ({
    case_id: r.case_id,
    kind: r.kind,
    source: r.source,
    snippet: r.snippet ?? null,
    page_or_slide: r.page_or_slide ?? null,
    timestamp_ms: r.timestamp_ms ?? null,
    storage_path: r.storage_path ?? null,
    metadata: r.metadata ?? {},
  }));
  const { data, error } = await sb.from("evidence").insert(payload).select("id");
  if (error || !data) throw new Error(`insertEvidenceBatch failed: ${error?.message ?? "no rows"}`);
  return data.map((r: any) => r.id as string);
}

/** Insert a new verdict row from a CoreOutput. Returns the new verdict id (== evaluation_id). */
export async function insertVerdict(output: CoreOutput, createdBy?: string): Promise<string> {
  const sb = getSupabase();
  // avatar_script comes from the L2 output. We persist the long form for
  // HeyGen so editors get the full text, with a fallback to whatever string
  // form is stored on the output.
  const avatarScriptText = (() => {
    const s = (output as any).avatar_script_structured;
    if (s?.long) return String(s.long);
    if (s?.short) return String(s.short);
    if (typeof output.avatar_script === "string") return output.avatar_script;
    return "";
  })();
  const { data, error } = await sb
    .from("verdicts")
    .insert({
      case_id: output.case_id,
      block_id: output.block_code,
      total_score: output.l2.total_score,
      award_level: output.l2.award_level,
      one_paragraph_verdict: output.l2.one_paragraph_verdict,
      criteria_scores: criteriaScoresToRow(output.l2.criteria_scores),
      missing_evidence: output.missing_evidence ?? [],
      consistency_check_passed: output.consistency_check_passed,
      methodology_hash: output.methodology_hash,
      anchors_hash: output.anchors_hash,
      prompt_hash: output.prompt_hash,
      input_hash: output.input_hash,
      model_id: output.model_id,
      approval_state: "pending",
      created_by: createdBy ?? null,
      avatar_script: avatarScriptText,
      avatar_status: "awaiting_review",
      avatar_updated_at: new Date().toISOString(),
    })
    .select("id")
    .single();
  if (error || !data) throw new Error(`insertVerdict failed: ${error?.message ?? "no row"}`);
  await updateCaseStatus(output.case_id, "scored");
  return data.id as string;
}

/** Update avatar_script on a verdict (Grand Moderator edits the speech text). */
export async function setVerdictSpeech(verdictId: string, script: string): Promise<{ case_id: string } | null> {
  const sb = getSupabase();
  const { data, error } = await sb
    .from("verdicts")
    .update({ avatar_script: script, avatar_updated_at: new Date().toISOString() })
    .eq("id", verdictId)
    .select("case_id")
    .maybeSingle();
  if (error) throw new Error(`setVerdictSpeech failed: ${error.message}`);
  return data ? { case_id: data.case_id } : null;
}

/** Mark a verdict approved + transition avatar pipeline to 'approved' (next stage will start the HeyGen render). */
export async function setVerdictApprovedForRender(verdictId: string): Promise<{ case_id: string } | null> {
  const sb = getSupabase();
  const { data, error } = await sb
    .from("verdicts")
    .update({
      approval_state: "approved",
      avatar_status: "approved",
      avatar_updated_at: new Date().toISOString(),
    })
    .eq("id", verdictId)
    .select("case_id")
    .maybeSingle();
  if (error) throw new Error(`setVerdictApprovedForRender failed: ${error.message}`);
  if (data?.case_id) await updateCaseStatus(data.case_id, "approved");
  return data ? { case_id: data.case_id } : null;
}

/** Update video pipeline state — used by the HeyGen worker once a render finishes. */
export async function setVerdictAvatarVideo(
  verdictId: string,
  args: { url?: string | null; status: AvatarStatus; video_id?: string | null; error?: string | null }
): Promise<void> {
  const sb = getSupabase();
  const update: Record<string, unknown> = {
    avatar_status: args.status,
    avatar_updated_at: new Date().toISOString(),
  };
  if (args.url !== undefined) update.avatar_video_url = args.url;
  if (args.video_id !== undefined) update.avatar_video_id = args.video_id;
  if (args.error !== undefined) update.avatar_error = args.error;
  const { error } = await sb.from("verdicts").update(update).eq("id", verdictId);
  if (error) throw new Error(`setVerdictAvatarVideo failed: ${error.message}`);
}

/** All verdicts currently rendering — used by the background poller. */
export async function listRenderingVerdicts(): Promise<
  Array<{ id: string; case_id: string; avatar_video_id: string | null }>
> {
  const sb = getSupabase();
  const { data, error } = await sb
    .from("verdicts")
    .select("id, case_id, avatar_video_id")
    .eq("avatar_status", "rendering")
    .not("avatar_video_id", "is", null);
  if (error) throw new Error(`listRenderingVerdicts failed: ${error.message}`);
  return (data ?? []) as Array<{ id: string; case_id: string; avatar_video_id: string | null }>;
}

/** Read current avatar_script for a verdict — needed by approve-and-render to send to HeyGen. */
export async function getVerdictAvatarScript(verdictId: string): Promise<string | null> {
  const sb = getSupabase();
  const { data, error } = await sb
    .from("verdicts")
    .select("avatar_script")
    .eq("id", verdictId)
    .maybeSingle();
  if (error) throw new Error(`getVerdictAvatarScript failed: ${error.message}`);
  return data?.avatar_script ?? null;
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Append a row to public.audit_log. Best-effort: failures are logged but do not throw.
 *  Non-UUID actor_id values are demoted to null + recorded under details.actor_label so
 *  the audit row still lands (e.g. for smoke tests or service identities without a UUID).
 */
export async function appendAuditLog(args: {
  action: string;
  entity_type?: string;
  entity_id?: string;
  actor_id?: string;
  actor_role?: "admin" | "reviewer" | "moderator" | "observer";
  details?: Record<string, unknown>;
}): Promise<void> {
  try {
    const sb = getSupabase();
    const validUuid = args.actor_id && UUID_RE.test(args.actor_id);
    const details: Record<string, unknown> = { ...(args.details ?? {}) };
    if (args.actor_id && !validUuid) details.actor_label = args.actor_id;
    const { error } = await sb.from("audit_log").insert({
      action: args.action,
      entity_type: args.entity_type ?? null,
      entity_id: args.entity_id ?? null,
      actor_id: validUuid ? args.actor_id : null,
      actor_role: args.actor_role ?? null,
      details,
    });
    if (error) console.warn("audit_log insert failed:", error.message);
  } catch (e) {
    console.warn("audit_log insert threw:", e);
  }
}

function rowToCoreOutput(v: VerdictRow): CoreOutput {
  return {
    case_id: v.case_id,
    methodology_hash: v.methodology_hash,
    anchors_hash: v.anchors_hash,
    prompt_hash: v.prompt_hash,
    input_hash: v.input_hash,
    model_id: v.model_id,
    block_code: v.block_id,
    nomination_code: "",
    l2: {
      criteria_scores: (v.criteria_scores ?? []).map((c) => ({
        criterion: c.criterion_id,
        score: c.score,
        rationale: c.rationale,
        evidence_ids: c.evidence_ids ?? [],
      })),
      block_score: v.total_score,
      total_score: v.total_score,
      award_level: v.award_level,
      one_paragraph_verdict: v.one_paragraph_verdict,
    },
    evidence: [],
    missing_evidence: v.missing_evidence ?? [],
    key_quotes: [],
    avatar_script: "",
    consistency_check_passed: v.consistency_check_passed,
  };
}

export async function getVerdict(verdictId: string): Promise<StoredEvaluation | null> {
  const sb = getSupabase();
  const { data, error } = await sb.from("verdicts").select("*").eq("id", verdictId).maybeSingle();
  if (error) throw new Error(`getVerdict failed: ${error.message}`);
  if (!data) return null;
  const row = data as VerdictRow;
  return {
    evaluation_id: row.id,
    case_id: row.case_id,
    created_at: row.created_at,
    output: rowToCoreOutput(row),
  };
}

/** Status of the avatar video pipeline for a given verdict. Tracked client-side
 *  via the verdict's approval_state and the presence of `output.avatar_script`
 *  / a future `avatar_video_url` column. Until the column exists, status is
 *  derived heuristically. */
export type AvatarStatus =
  | "scoring"
  | "awaiting_review"
  | "approved"
  | "rendering"
  | "ready"
  | "failed";

export async function listVerdicts(opts: { limit?: number; nomination?: string } = {}): Promise<
  Array<{
    evaluation_id: string;
    case_id: string;
    created_at: string;
    award_level: VerdictRow["award_level"];
    total_score: number;
    approval_state: VerdictRow["approval_state"];
    project_name?: string;
    nomination_code?: string;
    avatar_status: AvatarStatus;
    avatar_video_url: string | null;
    avatar_script: string | null;
    one_paragraph_verdict: string | null;
  }>
> {
  const sb = getSupabase();
  const limit = opts.limit ?? 200;
  let q = sb
    .from("verdicts")
    .select(
      "id, case_id, created_at, award_level, total_score, approval_state, one_paragraph_verdict, avatar_script, avatar_video_url, avatar_video_id, avatar_status, avatar_error, cases!inner(project_name, nomination_id)"
    )
    .order("created_at", { ascending: false })
    .limit(limit);
  // Server-side filter by nomination code (D01/D10/D13/D15) — Moderator
  // screens use this so they only see their category.
  if (opts.nomination) q = q.eq("cases.nomination_id", opts.nomination);
  const { data, error } = await q;
  if (error) throw new Error(`listVerdicts failed: ${error.message}`);
  return (data ?? []).map((r: any) => {
    // Use the persisted avatar_status if present; otherwise fall back to the
    // approval_state-derived heuristic for legacy rows that pre-date the
    // avatar columns.
    const persisted = r.avatar_status as AvatarStatus | null;
    let avatarStatus: AvatarStatus;
    if (persisted) {
      avatarStatus = persisted;
    } else if (r.approval_state === "approved") {
      avatarStatus = r.avatar_video_url ? "ready" : "approved";
    } else if (r.approval_state === "rejected") {
      avatarStatus = "failed";
    } else {
      avatarStatus = "awaiting_review";
    }
    return {
      evaluation_id: r.id,
      case_id: r.case_id,
      created_at: r.created_at,
      award_level: r.award_level,
      total_score: Number(r.total_score),
      approval_state: r.approval_state,
      project_name: r.cases?.project_name ?? undefined,
      nomination_code: r.cases?.nomination_id ?? undefined,
      avatar_status: avatarStatus,
      avatar_video_url: r.avatar_video_url ?? null,
      avatar_script: r.avatar_script ?? null,
      one_paragraph_verdict: r.one_paragraph_verdict ?? null,
    };
  });
}

/** Evidence row exposed via the rich verdict endpoint. */
export interface EvidenceRow {
  id: string;
  case_id: string;
  kind: NewEvidenceInput["kind"];
  source: string;
  snippet: string | null;
  page_or_slide: number | null;
  storage_path: string | null;
}

/** Fetch evidence rows for a case (used by the verdict-with-evidence endpoint). */
export async function listEvidenceForCase(caseId: string): Promise<EvidenceRow[]> {
  const sb = getSupabase();
  const { data, error } = await sb
    .from("evidence")
    .select("id, case_id, kind, source, snippet, page_or_slide, storage_path")
    .eq("case_id", caseId);
  if (error) throw new Error(`listEvidenceForCase failed: ${error.message}`);
  return (data ?? []) as EvidenceRow[];
}

/** Set approval_state on a verdict. Returns the updated row's case_id (for audit). */
export async function setVerdictApproval(
  verdictId: string,
  state: VerdictRow["approval_state"]
): Promise<{ case_id: string; previous: VerdictRow["approval_state"] } | null> {
  const sb = getSupabase();
  // Read previous state so the audit log can capture the transition.
  const { data: prev, error: prevErr } = await sb
    .from("verdicts")
    .select("case_id, approval_state")
    .eq("id", verdictId)
    .maybeSingle();
  if (prevErr) throw new Error(`setVerdictApproval read failed: ${prevErr.message}`);
  if (!prev) return null;
  const { error } = await sb.from("verdicts").update({ approval_state: state }).eq("id", verdictId);
  if (error) throw new Error(`setVerdictApproval failed: ${error.message}`);
  if (state === "approved") {
    await updateCaseStatus(prev.case_id, "approved");
  }
  return { case_id: prev.case_id, previous: prev.approval_state };
}

/** Get the rich verdict row including raw approval_state — used by the API for reviewer UI. */
export async function getVerdictRichRow(verdictId: string): Promise<{
  evaluation_id: string;
  case_id: string;
  created_at: string;
  approval_state: VerdictRow["approval_state"];
  output: CoreOutput;
} | null> {
  const sb = getSupabase();
  const { data, error } = await sb.from("verdicts").select("*").eq("id", verdictId).maybeSingle();
  if (error) throw new Error(`getVerdictRichRow failed: ${error.message}`);
  if (!data) return null;
  const row = data as VerdictRow;
  return {
    evaluation_id: row.id,
    case_id: row.case_id,
    created_at: row.created_at,
    approval_state: row.approval_state,
    output: rowToCoreOutput(row),
  };
}
