import OpenAI from "openai";
import { createHash } from "crypto";
import type { CaseBundle } from "./types/case.js";
import type { MethodologyBlock, NominationDef } from "./types/methodology.js";
import type { CriterionScore, EvidenceGrade } from "./types/evaluation.js";
import { resolveCriterionWeights, scoreToAwardLevel, getMethodology } from "./methodologyLoader.js";
import { getAnchorSet, getSocialOutcomesAnchors } from "./anchorsLoader.js";
import { L2ResponseSchema, type L2Response } from "./types/l2Schema.js";
import { retrieveAnchors, renderAnchorBlock } from "./judgeAnchorsLoader.js";

/**
 * L2 scoring — Phase 3 implementation.
 *
 * What landed in Phase 3:
 *   - Strict zod validation of model JSON; one retry then fall back.
 *   - Evidence-id citation: prompt renders each evidence segment with a cite_key
 *     (E1, E2, ...) and the model is required to cite them in evidence_ids.
 *     Cite keys are mapped back to public.evidence row ids before persistence.
 *   - Evidence-grade caps: model can flag no_baseline / no_causality /
 *     no_attribution; results-type criteria are capped accordingly before
 *     scoreToAwardLevel runs.
 *   - prompt_hash + model_id stamped onto the L2 result for full reproducibility.
 *
 * Future: streaming partials for live UI; multi-judge ensemble; image-grounded
 * scoring on visual-craft criteria.
 */

export type AwardLevel = "gold" | "silver" | "bronze" | "shortlist" | "longlist";

export interface CapApplied {
  criterion: string;
  original_score: number;
  capped_score: number;
  reason: string;
}

export interface L2Result {
  criteria_scores: CriterionScore[];
  block_score: number;
  social_outcomes_score?: number;
  total_score: number;
  award_level: AwardLevel;
  one_paragraph_verdict: string;
  // avatar_script intentionally absent — generated by avatarSpeech.ts after caps fire.
  evidence_grade?: EvidenceGrade;
  caps_applied: CapApplied[];
  case_fatal_flaw?: string;
  why_not_higher_band_overall?: string;
  prompt_hash: string;
  model_id: string;
}

// EMPIRICAL distribution from SM_2025.json (Phase 1 analytics): real human
// jurors at the festival use the FULL 1–10 scale with confident spread.
// Project-level medians: gold=9.27, silver=7.78, bronze=5.82, shortlist=3.93,
// longlist=2.19. Individual judge scores span 1–10 with std ~3 for top jurors.
//
// This block tells the model what the human distribution actually looks like
// — not invented thresholds, just observed reality from 8777 evaluations.
const SCALE_BANDS = `
Шкала 1–10 — КАК НА САМОМ ДЕЛЕ ОЦЕНИВАЛИ ЧЛЕНЫ ЖЮРИ XXVI (это твой бенчмарк):

Эмпирическая медиана итогового балла на ПРОЕКТЫ-победители:
  • золото:    9.27   (диапазон по проектам: 8.8–9.9, по жюри: 7–10)
  • серебро:   7.78   (диапазон: 7.0–8.5, по жюри: 4.8–9.4)
  • бронза:    5.82   (диапазон: 5.0–6.7, по жюри: 3.3–8.0)
  • шорт-лист: 3.93   (диапазон: 3.1–4.8, по жюри: 2.0–6.5)
  • лонг-лист: 2.19   (диапазон: 1.6–2.8, по жюри: 1.0–4.6)

Регламент XXVII (обязательная привязка):
  • 9–10  балл → золото
  • 7–8   балл → серебро
  • 5–6   балл → бронза
  • 3–4   балл → шорт-лист
  • 1–2   балл → лонг-лист

Распределение реальных оценок: ~25% всех баллов в диапазоне 1–3, ~25% в 4–5,
~25% в 6–7, ~25% в 8–10. Никакой "безопасной середины" 4–6 — реальные эксперты
смело ставят и единицы, и десятки. Если ты группируешь все баллы в 4–6 —
это сбой, не оценка.
`.trim();

// Persona voice cloned from top-5 calibrated jurors (judges 8837, 8918, 9774,
// 10369, 9600 — corr ≥ 0.976 between their scores and final awards). Their
// actual writing patterns observed in Phase 2 analysis:
//   • Average comment length ~270 chars (not 600+).
//   • Direct opening verdict: "Шикарный кейс…", "Отличный пример…",
//     "Хороший крепкий кейс…", "Не очевидно, как…", "Слабая идея…".
//   • Structure: verdict → 2–3 strengths with named KPIs / craft elements →
//     "Но/Однако…" → specific named gap → optional category-fit comment.
//   • Russian colloquialisms ok ("крепкое серебро", "не дотягивает", "молодцы").
//   • No hedge filler, no "в целом", no "проект демонстрирует", no "уважаемые".
//   • Asks specific questions when evidence is thin: "В чём бенчмарк?",
//     "Какие KPI стояли?", "Откуда эти цифры?".
const HOSTILE_PERSONA = `
Ты — опытный член жюри Silver Mercury XXVII. Твой ориентир — стиль топ-5
калиброванных экспертов XXVI (их балл на кейсе предсказывал итоговую медаль с
корреляцией ≥0.97). Ты пишешь как они: коротко, прямо, с названными KPI, с
"крепкой" / "не дотягивает" / "не очевидно" вместо вежливого хеджирования.

Голос:
  • Открытие фразой-вердиктом: "Шикарный кейс…", "Отличный пример индустриального
    бенчмарка", "Хороший крепкий кейс", "Не очевидно, как…", "Слабая идея".
    НЕ "в целом", НЕ "проект демонстрирует", НЕ "уважаемое жюри".
  • После вердикта — 2–3 конкретных факта (KPI, ремесло, стратегия), затем
    "Но / Однако / Не хватило…" + конкретный пропущенный элемент.
  • Если данных мало — задавай прямые вопросы: "В чём бенчмарк?", "Какие KPI?",
    "Откуда эти цифры?", "Что это даёт бизнесу?". Это не риторика — это сигнал
    низкого балла.
  • Длина обоснования критерия: 150–350 символов. Это норма от реальных топ-жюри.
  • Готов к крайностям. Если кейс — это шедевр с отцифрованными результатами и
    бизнес-импактом, ставь 9–10 и пиши "Шикарный кейс". Если кейс — пустая
    риторика без цифр, ставь 1–2 и пиши "Слабый, не отцифрован, не фестивальный".

Поведение:
  • Ты СМОТРИШЬ на якоря (примеры реальных оценок ниже). Когда видишь похожий
    по силе кейс — выставляй похожий балл. Не "защищай свой средний балл" —
    привязывайся к якорям.
  • Маркетинговый жаргон без цифр ("уникальный", "беспрецедентный", "вирусный",
    "успешный") = балл 1–3 на критерии "результаты".
  • Конкретные числа + сравнение (vs прошлый период / рынок / цель) +
    атрибуция = балл 6+. Если ещё и оригинальная идея — балл 8+.
`.trim();

const ANTI_SYCOPHANCY_RULES = `
Жёсткие требования к ответу:

1. ПРИВЯЗКА К ЯКОРЯМ. Перед тем как выставить балл, сравни кейс с
   приведёнными ниже реальными примерами оценок топ-жюри. Если кейс по
   уровню похож на пример с баллом X — твой балл должен быть в той же
   полосе ±0.5. Якоря важнее любых других правил.

2. РАСПРЕДЕЛЕНИЕ БАЛЛОВ. В реальной выборке XXVI ~25% всех баллов было в
   диапазоне 1–3, ~25% в 4–5, ~25% в 6–7, ~25% в 8–10. Если все твои
   критерии в полосе 4–6 — ты не справился. Реальные эксперты используют
   всю шкалу.

3. ОБОСНОВАНИЕ КРИТЕРИЯ — 150–350 символов в стиле топ-жюри:
     • вердикт-открытие ("Шикарный кейс…", "Хороший крепкий…", "Слабая…"),
     • 1–2 конкретных факта (KPI, ремесло, числа, сравнения),
     • "Но/Однако/Не хватило…" + конкретный пропущенный элемент.
   Без вступлений "в целом", "проект демонстрирует". Без перечисления
   общих фраз без цифр.

4. EVIDENCE_GRADE — флаги true ТОЛЬКО при реальном отсутствии данных:
     • no_baseline=true → нет ни одного сравнения (vs прошлый период / рынок / цель).
     • no_causality=true → результат мог быть достигнут и без этой кампании.
     • no_attribution=true → результат относится к нескольким активностям сразу.
   "На всякий случай" не ставь — флаги применяют жёсткие потолки на балл.

5. why_not_higher_band и why_not_higher_band_overall — конкретно, какого
   KPI или элемента не хватает для следующей полосы. Без общих формулировок.

6. fatal_flaws / case_fatal_flaw — конкретный дефект, по одному предложению.
   "Безупречно" не принимается — у любого кейса есть слабые места.
`.trim();

/** Criteria treated as "results-type" for evidence-grade caps. Matches all
 *  XXVII methodology criterion ids whose semantics are "did this work" — caps
 *  apply regardless of whether the model also flagged evidence_grade for soft
 *  criteria like idea/strategy. */
const RESULTS_LIKE_CRITERIA = new Set([
  "results",
  "effectiveness_results",
  "impact",
]);
/** Pattern fallback so we don't silently miss future criterion ids that include
 *  "result" / "impact" / "effective". */
const RESULTS_LIKE_PATTERN = /(result|impact|effective)/i;
function isResultsLikeCriterion(id: string): boolean {
  return RESULTS_LIKE_CRITERIA.has(id) || RESULTS_LIKE_PATTERN.test(id);
}

/** Hard ceilings applied to results-type criteria when evidence quality is flagged. */
const EVIDENCE_GRADE_CAPS = {
  no_baseline: 6,
  no_causality: 5,
  no_attribution: 7,
} as const;

/**
 * Numeric-evidence floor for results-type criteria. Looks at the case's
 * project_results text and counts genuinely quantitative tokens (digits with
 * scale words, percentages, currency, multipliers). If the count is below a
 * threshold, results-type criteria are capped at 3 — a case that claims
 * "значительный рост охвата" without any numbers cannot earn a results score
 * higher than shortlist, no matter how convincing the prose is.
 *
 * This is code-level, not prompt-level — the model can't bypass it. Added
 * after the v4 backtest showed few-shot examples lifting weak cases (none →
 * silver) when no quantitative anchor existed.
 */
function countQuantitativeTokens(text: string): number {
  if (!text) return 0;
  const lower = text.toLowerCase();
  // Russian convention writes large numbers with thin-space separators
  // ("1 945 474"). Strip any whitespace that sits between digits so the
  // 4+digit detector and scale-suffix detectors see them as a single number.
  const dejoined = lower.replace(/(\d)[\s  ](\d)/g, "$1$2")
    .replace(/(\d)[\s  ](\d)/g, "$1$2") // run again to collapse 1 945 474 → 1945474
    .replace(/(\d)[\s  ](\d)/g, "$1$2");
  // Strip 4-digit years so "в 2024 году" doesn't read as a quantitative claim.
  const stripped = dejoined.replace(/\b(19|20)\d{2}\b/g, " ");
  let count = 0;
  // Percentages: 12%, 12.5%, 12 %.
  count += (stripped.match(/\d[\d.,]*\s*%/g) ?? []).length;
  // п.п. (percentage points) — common in Russian marketing reports.
  count += (stripped.match(/\d[\d.,]*\s*п\.?\s*п\.?/g) ?? []).length;
  // Currency / scale: 1,2 млн, 500 тыс, 5 млрд, 100 руб, $5, €100.
  count += (stripped.match(/\d[\d.,]*\s*(млн|млрд|тыс|тысяч|миллион|миллиард|руб|₽|\$|€|usd|eur)/g) ?? []).length;
  // Multipliers: x2, в 3 раза, в 5x, "5 раз дороже" (bare X раз form).
  count += (stripped.match(/(в\s+\d+[\d.,]*\s+раз)|(\bx\s*\d+)|(\d+\s*x\b)|(\b\d+[\d.,-]*\s+раз)/g) ?? []).length;
  // ROI / ROAS / CPM / CPC / CPV / CTR / CR with a number nearby.
  count += (stripped.match(/(romi|roas|roi|cpa|cpm|cpc|cpv|ctr|cr)\s*[:=]?\s*\d/g) ?? []).length;
  count += (stripped.match(/\d[\d.,]*\s*(romi|roas|roi|cpa|cpm|cpc|cpv|ctr|cr)\b/g) ?? []).length;
  // Counts with units. Expanded with content/media/time units that appear
  // in real D-nomination cases.
  count += (stripped.match(
    /\d[\d.,]*\s*(человек|чел\.?|клик|просмотр|показ|регистр|подписчик|пользоват|посет|охват|конверс|заявк|продаж|серий|эпизод|ролик|видео|песн|контакт|секунд|сек\.?|минут|мин\.?|час\.?|дн\.?|нед(ел)?|месяц|год\.?|товар|штук|шт\.?|сегмент|герой|геро|игрок|участник|сообщен|пост|публикац|урок)/g
  ) ?? []).length;
  // Bare big numbers (≥4 digits) that aren't years — likely impressions/reach.
  // Now catches "1945474" (was "1 945 474" pre-dejoin) too.
  count += (stripped.match(/\b\d{4,}\b/g) ?? []).length;
  return count;
}

/** Apply numeric-evidence floor: if results text has too few quantitative
 *  tokens, cap results-type criteria at 3. Returns mutated copy + log. */
function applyNumericEvidenceFloor(
  criteriaScores: CriterionScore[],
  bundle: CaseBundle
): { scores: CriterionScore[]; caps: CapApplied[] } {
  const caps: CapApplied[] = [];
  const resultsText = bundle.text_fields?.project_results ?? "";
  const tokenCount = countQuantitativeTokens(resultsText);
  // Tightened after v6 backtest: weak cases with 1-2 stray numbers were
  // still scoring 7+ on results. Now requires ≥3 quantitative tokens to
  // unlock anything above 2 on results-type criteria. Forces empty-evidence
  // cases into longlist territory regardless of prose quality.
  const THRESHOLD = 3;
  const FLOOR_CAP = 2;
  if (tokenCount >= THRESHOLD) return { scores: criteriaScores, caps };
  const next = criteriaScores.map((c) => ({ ...c }));
  for (const c of next) {
    if (!isResultsLikeCriterion(c.criterion)) continue;
    if (c.score > FLOOR_CAP) {
      caps.push({
        criterion: c.criterion,
        original_score: c.score,
        capped_score: FLOOR_CAP,
        reason: `numeric_evidence_floor (only ${tokenCount} quantitative tokens in project_results)`,
      });
      c.score = FLOOR_CAP;
    }
  }
  return { scores: next, caps };
}

function buildCaseText(bundle: CaseBundle): string {
  const parts: string[] = [];
  const tf = bundle.text_fields;
  if (tf.project_info) parts.push(`## Описание / контекст\n${tf.project_info}`);
  if (tf.project_results) parts.push(`## Результаты\n${tf.project_results}`);
  if (tf.project_strategy) parts.push(`## Стратегия\n${tf.project_strategy}`);
  if (tf.project_task) parts.push(`## Задача\n${tf.project_task}`);
  if (tf.project_targets) parts.push(`## Цели\n${tf.project_targets}`);
  if (tf.project_channels) parts.push(`## Каналы\n${tf.project_channels}`);
  if (tf.project_realisation) parts.push(`## Реализация\n${tf.project_realisation}`);
  if (bundle.extracted_text?.length) {
    parts.push(
      "## Доказательная база (используй cite_key в evidence_ids):\n" +
        bundle.extracted_text
          .map((s) => `[${s.cite_key ?? "?"}] (${s.source}): ${s.text.slice(0, 1500)}`)
          .join("\n\n")
    );
  }
  return parts.join("\n\n") || "(нет текста)";
}

function computeBlockScore(
  block: MethodologyBlock,
  nomination: NominationDef,
  criteriaScores: CriterionScore[]
): number {
  const weights = resolveCriterionWeights(block, nomination);
  const byId = new Map(criteriaScores.map((c) => [c.criterion, c.score]));
  let total = 0;
  let totalWeight = 0;
  for (const { id, weight } of weights) {
    const s = byId.get(id);
    if (typeof s === "number") {
      total += s * weight;
      totalWeight += weight;
    }
  }
  return totalWeight > 0 ? Math.round((total / totalWeight) * 10) / 10 : 0;
}

function applySocialFormula(blockScore: number, socialScore: number): number {
  return Math.round(((blockScore + socialScore) / 2) * 10) / 10;
}

/** Map cite_keys (E1, E2, …) cited by the model back to public.evidence row ids. */
function resolveCiteKeys(citeKeys: string[], bundle: CaseBundle): string[] {
  const lookup = new Map<string, string>();
  for (const seg of bundle.extracted_text ?? []) {
    if (seg.cite_key && seg.evidence_id) lookup.set(seg.cite_key, seg.evidence_id);
  }
  const out: string[] = [];
  for (const key of citeKeys) {
    const id = lookup.get(key);
    if (id) out.push(id);
  }
  return out;
}

/** Apply evidence-grade caps to results-type criteria. Returns mutated copy + log. */
function applyEvidenceGradeCaps(
  criteriaScores: CriterionScore[],
  grade: EvidenceGrade | undefined
): { scores: CriterionScore[]; caps: CapApplied[] } {
  if (!grade) return { scores: criteriaScores, caps: [] };
  const caps: CapApplied[] = [];
  const next = criteriaScores.map((c) => ({ ...c }));
  for (const c of next) {
    if (!isResultsLikeCriterion(c.criterion)) continue;
    let cap = 10;
    let reason = "";
    if (grade.no_attribution && EVIDENCE_GRADE_CAPS.no_attribution < cap) {
      cap = EVIDENCE_GRADE_CAPS.no_attribution;
      reason = "no_attribution";
    }
    if (grade.no_baseline && EVIDENCE_GRADE_CAPS.no_baseline < cap) {
      cap = EVIDENCE_GRADE_CAPS.no_baseline;
      reason = "no_baseline";
    }
    if (grade.no_causality && EVIDENCE_GRADE_CAPS.no_causality < cap) {
      cap = EVIDENCE_GRADE_CAPS.no_causality;
      reason = "no_causality";
    }
    if (reason && c.score > cap) {
      caps.push({ criterion: c.criterion, original_score: c.score, capped_score: cap, reason });
      c.score = cap;
    }
  }
  return { scores: next, caps };
}

function sha256_16(s: string): string {
  return "sha256-" + createHash("sha256").update(s).digest("hex").slice(0, 16);
}

/** Wrap an OpenAI call with exponential backoff on 429. Caps at 4 retries. */
async function callWith429Retry<T>(fn: () => Promise<T>): Promise<T> {
  const maxRetries = 4;
  for (let attempt = 0; attempt <= maxRetries; attempt += 1) {
    try {
      return await fn();
    } catch (err: unknown) {
      const e = err as { status?: number; message?: string };
      const is429 = e?.status === 429 || /\b429\b|rate limit/i.test(e?.message ?? "");
      if (!is429 || attempt === maxRetries) throw err;
      // Try to read retry-after hint from message; otherwise exponential.
      const m = e?.message?.match(/try again in (\d+(?:\.\d+)?)s/i);
      const waitMs = m ? Math.ceil(parseFloat(m[1]) * 1000) + 250 : 1500 * Math.pow(2, attempt);
      await new Promise((r) => setTimeout(r, waitMs));
    }
  }
  // Unreachable.
  throw new Error("callWith429Retry: exhausted");
}

export async function runL2(
  bundle: CaseBundle,
  block: MethodologyBlock,
  nomination: NominationDef,
  apiKey: string | undefined
): Promise<L2Result> {
  const modelId = process.env.OPENAI_MODEL ?? "gpt-4o-mini";
  if (!apiKey) return runL2Fallback(bundle, block, nomination, modelId);

  const caseText = buildCaseText(bundle);
  const weights = resolveCriterionWeights(block, nomination);
  const wByCriterion = new Map(weights.map((w) => [w.id, w.weight]));
  // Note: inline generic anchors removed in v7 — they contradicted the
  // empirical retrieved anchors below. The empirical anchors are the only
  // anchor source the model sees now.
  const criteriaList = block.criteria
    .filter((c) => (wByCriterion.get(c.id) ?? 0) > 0)
    .map((c) => {
      return `- ${c.id} (${c.name_ru}): вес ${wByCriterion.get(c.id) ?? 0}. ${c.description_ru}`;
    })
    .join("\n");

  const isSocial = nomination.is_social;
  const cfg = getMethodology();
  const socialCrit = cfg.social_formula.social_criterion;
  let socialClause = "";
  if (isSocial) {
    const sa = getSocialOutcomesAnchors();
    socialClause = `\nЭто СОЦИАЛЬНО-ОРИЕНТИРОВАННАЯ номинация. Дополнительно оцени критерий "${socialCrit.id}" (${socialCrit.name_ru}): ${socialCrit.description_ru}
Якоря для social_outcomes: 2 — ${sa["2"]} | 5 — ${sa["5"]} | 8 — ${sa["8"]}
Балл по шкале 1–10. Итоговый балл = среднее арифметическое стандартного балла блока и social_outcomes.`;
  }

  // Retrieve real top-jury anchors from the same nomination/block. These
  // become the per-case calibration reference — the model sees what
  // calibrated humans actually scored and how they wrote about similar
  // projects in the same category.
  const retrievedAnchors = retrieveAnchors(nomination.code, block.id, 1);
  const anchorBlock = renderAnchorBlock(retrievedAnchors);

  const sys = `${HOSTILE_PERSONA}

Кейс: блок ${block.code} (${block.name_ru}), номинация ${nomination.code} (${nomination.name_ru}).

Критерии блока (с весами для этой номинации):
${criteriaList}
${socialClause}

${SCALE_BANDS}

${anchorBlock}

${ANTI_SYCOPHANCY_RULES}

ПРОТОКОЛ ОЦЕНКИ — два шага в твоей голове, прежде чем заполнять JSON:

ШАГ 1 — КРИТИКА (без баллов).
Перед тем как ставить любой балл, мысленно перечисли:
  (a) 2–3 КОНКРЕТНЫЕ сильные стороны кейса с привязкой к цитатам/числам.
  (b) 2–4 КОНКРЕТНЫЕ слабости — чего не хватает, что подано размыто, какие
      KPI не закрыты, где маркетинг вместо результата.
  (c) Какие методологические дефекты есть (нет базы, нет атрибуции, нет
      причинно-следственной связи) — реально, а не "на всякий случай".
Без этого шага твои баллы будут средними и неотличимыми. Сделай этот шаг.

ШАГ 2 — БАЛЛ ПО КАЖДОМУ КРИТЕРИЮ.
Для КАЖДОГО критерия:
  (i) Выбери полосу 1–10 на основе SCALE_BANDS триггеров — какой триггер
      срабатывает (нет цифр / есть цифры без сравнения / есть всё / есть всё
      + оригинальность / + внешнее подтверждение).
  (ii) Внутри полосы выбери конкретный балл (например, в полосе 7–8: 7 если
       минимально соответствует триггеру, 8 если устойчиво).
  (iii) В rationale напиши ТРИ части в одном абзаце:
       — "Сильные стороны: ..." (2–3 факта),
       — "Слабые стороны: ..." (1–2 факта),
       — "Что нужно для следующей полосы: ..." (конкретно).
  (iv) why_not_higher_band и fatal_flaws заполни по результатам шага 1(b).

ЗАПРЕЩЕНО ставить балл, не пройдя оба шага. Запрещено писать rationale
без явных "Сильные стороны / Слабые стороны / Что нужно для следующей полосы".

ОБЯЗАТЕЛЬНО: для каждого критерия укажи evidence_ids — массив cite_key из
доказательной базы (например, ["E1", "E3"]). Если конкретных свидетельств нет,
верни пустой массив и снизь балл до ≤4.

Дополнительно оцени качество доказательной базы по результатам:
- no_baseline: true, если нет базы для сравнения (до/после, контрольная группа).
- no_causality: true, если нет причинно-следственной связи между активностью и результатом.
- no_attribution: true, если результат нельзя однозначно отнести именно к этому проекту.

one_paragraph_verdict: 2–3 предложения. Сначала вердикт (медаль), затем
главная причина — конкретно. Без вступлений типа "в целом" или "проект
демонстрирует". Прямо.

Не пиши avatar_script в этом ответе. Речь генерируется отдельно
после применения всех ограничений и расчёта итоговой медали.

Ответь строго в JSON:
{
  "criteria": [{
    "id": "...",
    "score": 1-10,
    "rationale": "...",
    "evidence_ids": ["E1", ...],
    "why_not_higher_band": "конкретно, чего не хватает для следующей полосы",
    "fatal_flaws": ["флоу 1", "флоу 2"]
  }],
  ${isSocial ? '"social_outcomes_score": 1-10, "social_outcomes_rationale": "...",' : ""}
  "evidence_grade": {"no_baseline": bool, "no_causality": bool, "no_attribution": bool, "rationale": "..."},
  "one_paragraph_verdict": "...",
  "case_fatal_flaw": "одно предложение — главный дефект кейса",
  "why_not_higher_band_overall": "почему этот кейс не заслуживает следующей медали"
}`;

  const prompt_hash = sha256_16(sys);
  const client = new OpenAI({ apiKey });

  let parsed: L2Response | null = null;
  for (let attempt = 0; attempt < 2 && !parsed; attempt += 1) {
    const reminder = attempt === 0
      ? ""
      : "\n\nПРЕДЫДУЩИЙ ОТВЕТ НЕ ПРОШЁЛ ВАЛИДАЦИЮ. Верни строго JSON по схеме выше — все поля обязательны, score в [1..10].";
    const raw = await callWith429Retry(async () =>
      client.chat.completions.create({
        model: modelId,
        messages: [
          { role: "system", content: sys + reminder },
          { role: "user", content: `Кейс:\n\n${caseText.slice(0, 12000)}` },
        ],
        response_format: { type: "json_object" },
        temperature: 0,
      })
    );
    const content = raw?.choices?.[0]?.message?.content;
    if (!content) continue;
    try {
      const json = JSON.parse(content);
      parsed = L2ResponseSchema.parse(json);
    } catch (err) {
      console.warn(`L2 JSON validation failed (attempt ${attempt + 1}):`, (err as Error).message);
    }
  }

  if (!parsed) return runL2Fallback(bundle, block, nomination, modelId, prompt_hash);

  // Map criteria from model output → CriterionScore, dropping unknown ids.
  const validIds = new Set(block.criteria.map((c) => c.id));
  const seen = new Set<string>();
  const criteria_scores: CriterionScore[] = [];
  for (const item of parsed.criteria) {
    if (!validIds.has(item.id) || seen.has(item.id)) continue;
    seen.add(item.id);
    const score = Math.max(1, Math.min(10, Math.round(item.score * 10) / 10));
    criteria_scores.push({
      criterion: item.id,
      score,
      rationale: item.rationale,
      evidence_ids: resolveCiteKeys(item.evidence_ids ?? [], bundle),
      why_not_higher_band: item.why_not_higher_band,
      fatal_flaws: item.fatal_flaws,
    });
  }
  // Pad missing criteria with a conservative penalty.
  for (const c of block.criteria) {
    if ((wByCriterion.get(c.id) ?? 0) === 0) continue;
    if (criteria_scores.some((s) => s.criterion === c.id)) continue;
    criteria_scores.push({
      criterion: c.id,
      score: 2,
      rationale: "Штраф: критерий отсутствовал в ответе модели.",
      evidence_ids: [],
      why_not_higher_band: "Модель не дала ответ — нет оснований для более высокого балла.",
      fatal_flaws: ["Отсутствие оценки по критерию в ответе модели."],
    });
  }

  // Anti-sycophancy: only the strict bunching guard (≥80% identical AND no
  // evidence anywhere). The earlier flat-distribution penalty was firing on
  // legitimately-weak cases where flat low scores are correct, contributing
  // to the "everything collapses to one band" failure mode seen in the
  // 2026-04-28 backtest. Removed.
  if (criteria_scores.length >= 3) {
    const scores = criteria_scores.map((s) => s.score);
    const scoreCounts = new Map<number, number>();
    for (const s of scores) scoreCounts.set(s, (scoreCounts.get(s) ?? 0) + 1);
    const maxBunch = Math.max(...scoreCounts.values());
    const bunchRatio = maxBunch / scores.length;
    const allEvidenceMissing = criteria_scores.every((s) => (s.evidence_ids ?? []).length === 0);
    if (bunchRatio >= 0.8 && allEvidenceMissing) {
      for (const s of criteria_scores) {
        s.score = Math.max(1, s.score - 2);
        s.rationale = `[anti-bunching:-2] ${s.rationale}`;
      }
    }
  }
  criteria_scores.sort(
    (a, b) =>
      block.criteria.findIndex((x) => x.id === a.criterion) -
      block.criteria.findIndex((x) => x.id === b.criterion)
  );

  // Apply evidence-grade caps before computing block score.
  const evidence_grade = parsed.evidence_grade;
  const { scores: gradeCappedScores, caps: gradeCaps } = applyEvidenceGradeCaps(criteria_scores, evidence_grade);

  // Numeric-evidence floor: if project_results has too few quantitative
  // tokens, results-type criteria can't exceed 3 regardless of model output.
  // This is the structural counterpart to the band-trigger SCALE_BANDS prompt
  // — without it, well-written empty cases drift into bronze/silver.
  const { scores: cappedScores, caps: floorCaps } = applyNumericEvidenceFloor(gradeCappedScores, bundle);
  const caps_applied: CapApplied[] = [...gradeCaps, ...floorCaps];

  let block_score = computeBlockScore(block, nomination, cappedScores);

  // Block-level evidence cap: if the model flagged 2+ evidence-grade defects,
  // the case can't credibly cross into gold territory. Loosened from the
  // initial values (4.9/3.5) after a 15-case backtest revealed all bands
  // collapsed to shortlist; these levels still keep weak-evidence cases out
  // of gold while letting genuinely strong silver cases through if the per-
  // criterion caps already cut the results-side scores.
  if (evidence_grade) {
    const flagsSet = [evidence_grade.no_baseline, evidence_grade.no_causality, evidence_grade.no_attribution].filter(Boolean).length;
    // 2 flags → top-of-bronze ceiling (5.5). 3 flags → mid-shortlist (4.5).
    // Per-criterion caps already constrain results-type criteria; the
    // block-level cap is a backstop, not the primary mechanism.
    if (flagsSet >= 2 && block_score > 5.5) {
      caps_applied.push({
        criterion: "(block_score)",
        original_score: block_score,
        capped_score: 5.5,
        reason: `evidence_grade_${flagsSet}_flags`,
      });
      block_score = 5.5;
    }
    if (flagsSet === 3 && block_score > 4.5) {
      caps_applied.push({
        criterion: "(block_score)",
        original_score: block_score,
        capped_score: 4.5,
        reason: "evidence_grade_all_flags",
      });
      block_score = 4.5;
    }
  }

  let total_score = block_score;
  let social_outcomes_score: number | undefined;
  if (isSocial) {
    const s =
      typeof parsed.social_outcomes_score === "number"
        ? Math.max(1, Math.min(10, Math.round(parsed.social_outcomes_score * 10) / 10))
        : 3;
    social_outcomes_score = s;
    total_score = applySocialFormula(block_score, s);
  }
  const award_level = scoreToAwardLevel(total_score);

  return {
    criteria_scores: cappedScores,
    block_score,
    social_outcomes_score,
    total_score,
    award_level,
    one_paragraph_verdict: parsed.one_paragraph_verdict,
    evidence_grade,
    caps_applied,
    case_fatal_flaw: parsed.case_fatal_flaw,
    why_not_higher_band_overall: parsed.why_not_higher_band_overall,
    prompt_hash,
    model_id: modelId,
  };
}

function runL2Fallback(
  bundle: CaseBundle,
  block: MethodologyBlock,
  nomination: NominationDef,
  modelId: string,
  prompt_hash: string = "sha256-fallback"
): L2Result {
  const weights = resolveCriterionWeights(block, nomination);
  const validWeightIds = new Set(weights.map((w) => w.id));
  const criteria_scores: CriterionScore[] = block.criteria
    .filter((c) => validWeightIds.has(c.id))
    .map((c) => ({
      criterion: c.id,
      score: 3,
      rationale: `Заглушка (L2 без API ключа или невалидный JSON). Консервативная оценка. Критерий: ${c.name_ru}.`,
      evidence_ids: [],
      why_not_higher_band: "Нет данных модели для обоснования более высокого балла.",
      fatal_flaws: ["Заглушка: оценка не выполнена реальной моделью."],
    }));
  const block_score = computeBlockScore(block, nomination, criteria_scores);
  let total_score = block_score;
  let social_outcomes_score: number | undefined;
  if (nomination.is_social) {
    social_outcomes_score = 3;
    total_score = applySocialFormula(block_score, social_outcomes_score);
  }
  const award_level = scoreToAwardLevel(total_score);
  const projectName = bundle.metadata.project_name ?? bundle.metadata.case_id;
  return {
    criteria_scores,
    block_score,
    social_outcomes_score,
    total_score,
    award_level,
    one_paragraph_verdict: `Синтетическая оценка (заглушка). Кейс «${projectName}»: итоговая награда по весам блока ${block.code}, номинация ${nomination.code}: ${award_level}.`,
    evidence_grade: undefined,
    caps_applied: [],
    case_fatal_flaw: "Заглушка: настоящая оценка не выполнялась.",
    why_not_higher_band_overall: "Заглушка: модель не оценивала кейс.",
    prompt_hash,
    model_id: modelId,
  };
}
